In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings
warnings.filterwarnings("ignore")
sns.set()
import statsmodels.api as sm 
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.model_selection import train_test_split

In [2]:
#y=mx+c
big=pd.read_csv("new_train")

In [3]:
big.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,1998,Medium,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,1987,High,Tier 3,Supermarket Type1,994.7052

In [4]:
big["Item_Type"]=big["Item_Type"].map(big["Item_Type"].value_counts(normalize=True))

In [5]:
big.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,0.080019,249.8092,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,0.052212,48.2692,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,0.049865,141.6180,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,0.144550,182.0950,1998,Medium,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,0.106770,53.8614,1987,High,Tier 3,Supermarket Type1,994.7052

In [6]:
y=big["Item_Outlet_Sales"]
X=pd.get_dummies(big.drop(["Item_Outlet_Sales",'Item_Identifier'],axis=1),columns=["Outlet_Size","Outlet_Location_Type","Outlet_Type","Item_Fat_Content"],drop_first=True)

In [7]:
big.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

In [8]:
Xc=sm.add_constant(X)
Xc

,const,Item_Weight,Item_Visibility,Item_Type,Item_MRP,Outlet_Establishment_Year,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3,Item_Fat_Content_Regular
0,1.0,9.300,0.016047,0.080019,249.8092,1999,1,0,0,0,1,0,0,0
1,1.0,5.920,0.019278,0.052212,48.2692,2009,1,0,0,1,0,1,0,1
2,1.0,17.500,0.016760,0.049865,141.6180,1999,1,0,0,0,1,0,0,0
3,1.0,19.200,0.000000,0.144550,182.0950,1998,1,0,0,1,0,0,0,1
4,1.0,8.930,0.000000,0.106770,53.8614,1987,0,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,1.0,6.865,0.056783,0.140795,214.5218,1987,0,0,0,1,1,0,0,0
8519,1.0,8.380,0.046982,0.076030,108.1570,2002,0,1,1,0,1,0,0,1
8520,1.0,10.600,0.035186,0.061011,85.1224,2004,0,1,1,0,1,0,0,0
8521,1.0,7.210,0.145221,0.140795,103.1332,2009,1,0,0,1,0,1,0,1
8522,1.0,14.800,0.044878,0.052212,75.4670,1997,0,1,0,0,1,0,0,0

In [9]:
model=sm.OLS(y,Xc).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:      Item_Outlet_Sales   R-squared:                       0.563
Model:                            OLS   Adj. R-squared:                  0.562
Method:                 Least Squares   F-statistic:                     843.2
Date:                Thu, 26 Jan 2023   Prob (F-statistic):               0.00
Time:                        00:46:10   Log-Likelihood:                -71996.
No. Observations:                8523   AIC:                         1.440e+05
Df Residuals:                    8509   BIC:                         1.441e+05
Df Model:                          13
Covariance Type:            nonrobust
=================================================================================================
                                    coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
const                         -6.169e+04   2.05e+04     -3.015      0.003   -1.02e+05   -2.16e+04
Item_Weight                       0.0288      2.640      0.011      0.991      -5.146       5.203
Item_Visibility                -289.8043    247.833     -1.169      0.242    -775.617     196.009
Item_Type                        -2.7435    307.395     -0.009      0.993    -605.312     599.825
Item_MRP                         15.5661      0.197     79.117      0.000      15.180      15.952
Outlet_Establishment_Year        30.5571     10.418      2.933      0.003      10.135      50.979
Outlet_Size_Medium             -752.8745    254.703     -2.956      0.003   -1252.154    -253.595
Outlet_Size_Small              -789.6506    246.591     -3.202      0.001   -1273.028    -306.273
Outlet_Location_Type_Tier 2    -163.4816     87.527     -1.868      0.062    -335.055       8.092
Outlet_Location_Type_Tier 3    -452.8750    143.498     -3.156      0.002    -734.166    -171.584
Outlet_Type_Supermarket Type1  1520.9543    139.889     10.873      0.000    1246.739    1795.170
Outlet_Type_Supermarket Type2  1294.1499    130.051      9.951      0.000    1039.219    1549.081
Outlet_Type_Supermarket Type3  3754.7185    148.679     25.254      0.000    3463.272    4046.164
Item_Fat_Content_Regular         51.8329     25.748      2.013      0.044       1.361     102.305
==============================================================================
Omnibus:                      960.217   Durbin-Watson:                   2.003
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2285.702
Skew:                           0.667   Prob(JB):                         0.00
Kurtosis:                       5.157   Cond. No.                     3.35e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.35e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
lir=LinearRegression()
model2=lir.fit(X_train,y_train)

In [12]:
ypred=model2.predict(X_test)

In [13]:
np.sqrt(mean_squared_error(y_test,ypred))

1068.4209294632444

In [14]:
r2_score(y_test,ypred)

0.5800088836386452